# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170527_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='description_pre',
        ),
    ]
