# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 12:26
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170527_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_common',
            field=froala_editor.fields.FroalaField(blank=True, help_text=b"Description to show when pre and post aren'nt available.", null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_post',
            field=froala_editor.fields.FroalaField(blank=True, help_text=b'Post event description; like thanking the attendees.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_pre',
            field=froala_editor.fields.FroalaField(blank=True, help_text=b'Pre-event description; like invitations, how to reach there, etc.', null=True),
        ),
    ]
