# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170527_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description_common',
            field=froala_editor.fields.FroalaField(blank=True, help_text="Description to show when pre and post aren'nt available.", null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_post',
            field=froala_editor.fields.FroalaField(blank=True, help_text='Post event description; like thanking the attendees.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_pre',
            field=froala_editor.fields.FroalaField(blank=True, help_text='Pre-event description; like invitations, how to reach there, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
