# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 10:56
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20170911_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
