# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 10:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0042_auto_20170109_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='alternative_names',
        ),
        migrations.AddField(
            model_name='player',
            name='alt_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
