# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0043_auto_20170505_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
