# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0044_auto_20170525_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='image',
            field=models.ImageField(upload_to=b'wallpapers/'),
        ),
    ]
