# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0045_auto_20170527_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='friendly',
            field=models.BooleanField(default=False),
        ),
    ]
