# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 12:38
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0047_auto_20170911_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='crest',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='crests/'),
        ),
    ]
