# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20170914_2123'),
        ('stats', '0048_auto_20170915_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='live_screening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
        ),
    ]
