# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0050_auto_20170922_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='ls_endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
