# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0052_auto_20170928_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='has_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='has_table',
            field=models.BooleanField(default=False),
        ),
    ]
