# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0053_auto_20170928_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='assistant_referee_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='assistant_referee_2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='competition_year',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_referee',
        ),
        migrations.RemoveField(
            model_name='match',
            name='referee',
        ),
        migrations.RemoveField(
            model_name='playercareersession',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playercareersession',
            name='team',
        ),
        migrations.RemoveField(
            model_name='redcard',
            name='match',
        ),
        migrations.RemoveField(
            model_name='redcard',
            name='player',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='city',
        ),
        migrations.RemoveField(
            model_name='staffcareersession',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staffcareersession',
            name='team',
        ),
        migrations.RemoveField(
            model_name='statset',
            name='match',
        ),
        migrations.RemoveField(
            model_name='statset',
            name='team',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='subbed_in',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='subbed_out',
        ),
        migrations.DeleteModel(
            name='Wallpaper',
        ),
        migrations.RemoveField(
            model_name='yellowcard',
            name='match',
        ),
        migrations.RemoveField(
            model_name='yellowcard',
            name='player',
        ),
        migrations.RemoveField(
            model_name='team',
            name='stadium',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Official',
        ),
        migrations.DeleteModel(
            name='PlayerCareerSession',
        ),
        migrations.DeleteModel(
            name='RedCard',
        ),
        migrations.DeleteModel(
            name='Stadium',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffCareerSession',
        ),
        migrations.DeleteModel(
            name='StatSet',
        ),
        migrations.DeleteModel(
            name='Substitution',
        ),
        migrations.DeleteModel(
            name='YellowCard',
        ),
    ]
