# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0054_auto_20170928_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchresult',
            name='fixture',
        ),
        migrations.AlterField(
            model_name='fixture',
            name='competition_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='stats.CompetitionYear'),
        ),
        migrations.DeleteModel(
            name='MatchResult',
        ),
    ]
