# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170603_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
