# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 10:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_message_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsetting',
            name='email',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='contactsetting',
            name='fax',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='contactsetting',
            name='phone',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
    ]
