# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20170603_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsetting',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
