# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0044_auto_20170525_1913'),
        ('gallery', '0004_auto_20160914_1529'),
        ('events', '0005_event_featured'),
        ('post', '0006_auto_20160824_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='gallery.Album'),
        ),
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='events.Event'),
        ),
        migrations.AddField(
            model_name='post',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='stats.Fixture'),
        ),
    ]
