# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20170911_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/'),
        ),
    ]
