# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 15:38
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20170914_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='partners/'),
        ),
    ]
