# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 10:22
from __future__ import unicode_literals

from django.db import migrations
import muscn.utils.location


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20170914_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='location',
            field=muscn.utils.location.LocationField(blank=True, max_length=255),
        ),
    ]
