# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_partner_partnership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partnership',
            field=models.CharField(default='Partner', max_length=255),
        ),
    ]
