# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20170922_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='active',
        ),
        migrations.AddField(
            model_name='partner',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='pickup_location',
            field=models.BooleanField(default=False),
        ),
    ]
