# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_auto_20170925_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='short_address',
            field=models.CharField(default='Kathmandu', max_length=255),
            preserve_default=False,
        ),
    ]
