# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_partner_short_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
