# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-01 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message to broadcast.')),
                ('remarks', models.TextField(blank=True, help_text='Admin notes.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
