# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-01 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0003_auto_20170201_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkmessage',
            old_name='error_message',
            new_name='response_message',
        ),
    ]
