# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-01 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0005_auto_20170201_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushmessage',
            name='title',
            field=models.CharField(default='Man Utd.', max_length=255),
        ),
    ]
