# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-02 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0006_auto_20170201_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushmessage',
            name='response_message',
            field=models.TextField(blank=True, help_text='FCM response.', null=True),
        ),
    ]
