# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 12:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0007_pushmessage_response_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushmessage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
