# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-09 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20161118_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_fee', models.FloatField(verbose_name=b'Membership Fee')),
                ('enable_esewa', models.BooleanField(default=True)),
                ('welcome_letter_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
