# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-09 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_membershipsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipsetting',
            name='membership_fee',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Membership Fee'),
        ),
    ]
