# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20170109_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsetting',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
