# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_membershipsetting_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='identification_file',
            field=models.FileField(blank=True, null=True, upload_to=b'identification_files/'),
        ),
    ]
