# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
