# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_newsletter_last_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardstatus',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Awaiting Print'), (2, 'Printed'), (3, 'Delivered')], default=1),
        ),
        migrations.AlterField(
            model_name='membership',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='identification_file',
            field=models.FileField(blank=True, null=True, upload_to='identification_files/'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('E', 'Expired')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='membershipsetting',
            name='membership_fee',
            field=models.FloatField(blank=True, null=True, verbose_name='Membership Fee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
