# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20170923_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Pending Payment', 'Pending Payment'), ('Pending Approval', 'Pending Approval'), ('Member', 'Member'), ('Expired', 'Expired')], default='Registered', max_length=30),
        ),
    ]
