# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import muscn.utils.football


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20170924_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardstatus',
            name='season',
            field=models.CharField(default=muscn.utils.football.season, max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='cardstatus',
            unique_together=set([('user', 'season')]),
        ),
    ]
