# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20170924_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_statuses', to=settings.AUTH_USER_MODEL),
        ),
    ]
