# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_cardstatus_pickup_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLoginToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('token', models.TextField()),
                ('uid', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cardstatus',
            name='status',
            field=models.CharField(choices=[('Awaiting Approval', 'Awaiting Approval'), ('Awaiting Print', 'Awaiting Print'), ('Printed', 'Printed'), ('Delivered', 'Delivered')], default='Awaiting Print', max_length=20),
        ),
    ]
