# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('users', '0043_auto_20170925_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallogintoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='SocialLoginToken',
        ),
        migrations.CreateModel(
            name='SocialLoginToken',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('socialaccount.socialtoken',),
        ),
    ]
