# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20170926_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel',
            field=models.CharField(default='Web', max_length=50),
        ),
    ]
