# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import muscn.utils.football


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20170927_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complimentary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardstatus',
            name='season',
            field=models.CharField(choices=[('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014')], default=muscn.utils.football.season, max_length=9),
        ),
    ]
