# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 11:36
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20170911_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
