# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160914_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=b'images/'),
        ),
    ]
