# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 11:36
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20170911_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/'),
        ),
    ]
