# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-09 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_receiptdata_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiptdata',
            options={'verbose_name_plural': 'Receipt Data'},
        ),
    ]
