# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20170109_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esewapayment',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
