# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20170505_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Date/Time'),
        ),
    ]
