# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20170523_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directpayment',
            name='receipt_no',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name=b'Receipt No. (If you paid directly to a representative)'),
        ),
    ]
