# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20170911_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='voucher_image',
            field=models.FileField(upload_to='voucher_images/'),
        ),
    ]
