# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_receiptdata_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
