# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_auto_20170924_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directpayment',
            name='receipt_no',
            field=models.PositiveIntegerField(null=True, verbose_name='Receipt No. (If you paid directly to a representative)'),
        ),
    ]
