# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributedkey',
            name='key',
            field=models.TextField(blank=True, default='xyz'),
            preserve_default=False,
        ),
    ]
